name = "agienginex-v1-7"
main = "main_worker.js"
compatibility_date = "2025-06-07"
compatibility_flags = []

[[kv_namespaces]]
binding = "MEMORY_KV"
id = "6cf28c1062ce4684a783c4db0dd7b6b2"

[vars]
# You do NOT need to define OPENAI_API_KEY or API_TOKEN here — they are set via wrangler secret put
