# wrangler.toml
# AGIengineX-v1.7 ONE STEP FULL 🚀

name = "agienginex-v1-7"
main = "main_worker.js"
compatibility_date = "2024-06-01"

# KV binding for memory
[[kv_namespaces]]
binding = "MEMORY_KV"
id = "YOUR_KV_NAMESPACE_ID" # will be auto-created by Wrangler if you use wrangler.toml with `wrangler kv:namespace create MEMORY_KV`

# Environment variables (secrets go here in Cloudflare)
[vars]
OPENAI_API_KEY = ""
API_TOKEN = ""
